server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.11.20.8:13001/mytestffff?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: ALWAYS #使用彩色日志输出，正式环境去除


